#!/bin/sh

#===============================================================================
# ossuary
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
echo "\
$(basename "$0") -m mount -f container
$(basename "$0") -m umount -f container"
exit 1
}

#===============================================================================
# error messages
#===============================================================================

ROOT_ERR="$(basename "$0") must be run as root"
WRONG_ARGS_ERR='wrong number of arguments passed to script'
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'


#===============================================================================
# check if script is run as root
#===============================================================================

[ "$(id -u)" -eq 0 ] || usage "${ROOT_ERR}"


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"

#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':m:f:h' opt
do
  case ${opt} in
     m) action="${OPTARG}";;
     f) container="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# functions
#===============================================================================

# mount function
mount_container () {
    [ -f "${container}" ] || usage "Container file not found"

    # attach the container to a vnd loopback device
    vnconfig vnd0 "${container}"

    # Attach the volume
    bioctl -c C -l vnd0a softraid0

    # mount the device
    mount /dev/sd2a /home/djwilcox/mnt

}

# umount function
umount_container () {
    [ -n "${container}" ] || usage "Container path required (-f)"

    # unmount device
    umount /home/djwilcox/mnt

    # detach the softraid crypto volume
    bioctl -d sd2

    # unconfigure the loopback device
    vnconfig -u vnd0
}

#===============================================================================
# mount and umount case statement
#===============================================================================

case "${action}" in
    mount) mount_container;;
    umount) umount_container;;
    *) usage;;
esac
